/**
 * Shared constants for the application.
 * Keeps page components clean and makes updates centralized.
 */

import { ComponentType } from "react";
import {
  Fingerprint,
  Coins,
  Shield,
  FileCheck,
  Lock,
  Sparkles,
} from "lucide-react";

/* ── Credential Data ───────────────────────────────────────────── */

export interface CredentialItem {
  id: number;
  title: string;
  description: string;
  collateralDiscount: string;
  rateDiscount: string;
  icon: ComponentType<{ className?: string }>;
  method: string;
}

export const CREDENTIAL_ITEMS: CredentialItem[] = [
  {
    id: 0,
    title: "Credit Score Bureau Attestation",
    description: "ZK-proof bureau attestation validating traditional credit score > 680.",
    collateralDiscount: "-25% Collateral",
    rateDiscount: "-1.8% Rate",
    icon: Fingerprint,
    method: "Enclave decryption over bureau API"
  },
  {
    id: 1,
    title: "Banking Asset Verification",
    description: "Proof of reserves and monthly cashflow verified via TEE open-banking.",
    collateralDiscount: "-20% Collateral",
    rateDiscount: "-1.2% Rate",
    icon: Coins,
    method: "Open Banking secure payload verification"
  },
  {
    id: 2,
    title: "KYC / Legal Identity Check",
    description: "Verified real-world identity linked privately to your on-chain address.",
    collateralDiscount: "-15% Collateral",
    rateDiscount: "-0.8% Rate",
    icon: Shield,
    method: "Government ID cryptographic attestation"
  },
  {
    id: 3,
    title: "On-Chain Repayment History",
    description: "Positive score generated by history of clean repayment in other lending vaults.",
    collateralDiscount: "-10% Collateral",
    rateDiscount: "-0.6% Rate",
    icon: FileCheck,
    method: "Base network historical trace scanning"
  },
  {
    id: 4,
    title: "Default Reporting Consent",
    description: "Borrower opts into TEE-encrypted default reporting trigger to credit bureaus.",
    collateralDiscount: "-8% Collateral",
    rateDiscount: "-0.4% Rate",
    icon: Lock,
    method: "Cryptographic Consent Encrypted Attestation"
  }
];

/* ── Step Configuration ────────────────────────────────────────── */

export const BORROW_STEPS = ["IDENTITY & TRUST", "TERMS & DURATION", "CONFIRM LOAN"];

/* ── Animation Variants ────────────────────────────────────────── */

export const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
      delayChildren: 0.3,
    },
  },
};

export const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      type: "spring" as const,
      stiffness: 100,
      damping: 20,
    },
  },
};

export const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

/* ── Feature Data ──────────────────────────────────────────────── */

export const HOME_FEATURES = [
  {
    step: "01",
    title: "Verify",
    desc: "Verify your bank details, credit score, or legal identity cryptographically via secure enclaves.",
    icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m7 11 2-2-2-2M11 19h10M15 9l2 2-2 2M3 13l2 2-2 2" /></svg>
  },
  {
    step: "02",
    title: "Attest",
    desc: "Attestations are recorded securely on-chain to your address, dynamically lowering your loan requirements.",
    icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /></svg>
  },
  {
    step: "03",
    title: "Borrow",
    desc: "Lock RLO token collateral and borrow USDC instantly from the lending pool based on your custom terms.",
    icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
  }
];

export const HOME_BENEFITS = [
  { title: "Composable Capital", icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" /></svg> },
  { title: "Non-Custodial", icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" /></svg> },
  { title: "Yield Recirculation", icon: <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 12a9 9 0 1 1-6.219-8.56" /></svg> }
];

export const HOME_STATS = [
  { label: "Credit Invisible", value: "32M", desc: "Reliable adults with no score." },
  { label: "TAM", value: "$5.1T", desc: "Unsecured consumer debt market." },
  { label: "Efficiency", value: "97%", desc: "Avg. digital repayment rates." },
  { label: "Speed", value: "< 3m", desc: "Average time to onchain credit." }
];

export const HOME_INFRA_FEATURES = [
  { title: "Verifiable Solvency", desc: "Pool liquidity and borrower health are 100% transparent and verifiable on Base Sepolia." },
  { title: "Deterministic Execution", desc: "Loan terms, interest accrual, and repayments are managed by immutable smart contracts." }
];
