"use client";

import { useState, useEffect, useMemo, ComponentType } from "react";
import Link from "next/link";
import { useAccount } from "wagmi";
import { parseUnits, formatUnits } from "viem";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Shield,
  Check,
  Lock,
  Sparkles,
  RefreshCw,
  Coins,
  Fingerprint,
  FileCheck,
  Plus,
  AlertCircle
} from "lucide-react";
import {
  useRialoPoolRead,
  useRialoBorrowWrite,
  useCredentialVerifierWrite,
  useRialoFaucets
} from "@/hooks/useContracts";
import { computeCollateralDetails } from "@/lib/pricing";
import { useToast } from "@/lib/providers/toast";

/* ── Step Indicator ────────────────────────────────────────────── */

function StepIndicator({ currentStep }: { currentStep: number }) {
  const steps = ["IDENTITY & TRUST", "TERMS & DURATION", "CONFIRM LOAN"];
  return (
    <div className="flex items-center justify-between mb-12 max-w-xl mx-auto px-4">
      {steps.map((label, i) => (
        <div key={i} className="flex flex-col items-center gap-2 flex-1 relative">
          {i > 0 && (
            <div
              className={`absolute top-2.5 right-1/2 left-[-50%] h-[1px] -z-10 transition-colors duration-500 ${
                i <= currentStep - 1 ? "bg-[var(--color-sage-dark)]" : "bg-[var(--bone-dark)] opacity-20"
              }`}
            />
          )}
          <div
            className={`w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-mono border transition-all duration-500 ${
              i <= currentStep - 1
                ? "bg-[var(--color-sage-dark)] border-[var(--color-sage-dark)] text-white scale-110 shadow-sm"
                : "bg-[var(--glass-bg)] border-[var(--bone-dark)] text-[var(--ink-muted)] opacity-50"
            }`}
          >
            {i + 1}
          </div>
          <span
            className={`text-[9px] font-mono tracking-wider transition-colors duration-300 ${
              i <= currentStep - 1 ? "text-[var(--ink)] font-bold" : "text-[var(--ink-muted)] opacity-30"
            }`}
          >
            {label}
          </span>
        </div>
      ))}
    </div>
  );
}

/* ── Credentials Data ───────────────────────────────────────────── */

interface CredentialItem {
  id: number;
  title: string;
  description: string;
  collateralDiscount: string;
  rateDiscount: string;
  icon: ComponentType<{ className?: string }>;
  method: string;
}

const CREDENTIAL_ITEMS: CredentialItem[] = [
  {
    id: 0,
    title: "Credit Score Bureau Attestation",
    description: "ZK-proof bureau attestation validating traditional credit score > 680.",
    collateralDiscount: "-25% Collateral",
    rateDiscount: "-1.8% Rate",
    icon: Fingerprint,
    method: "Enclave decryption over bureau API"
  },
  {
    id: 1,
    title: "Banking Asset Verification",
    description: "Proof of reserves and monthly cashflow verified via TEE open-banking.",
    collateralDiscount: "-20% Collateral",
    rateDiscount: "-1.2% Rate",
    icon: Coins,
    method: "Open Banking secure payload verification"
  },
  {
    id: 2,
    title: "KYC / Legal Identity Check",
    description: "Verified real-world identity linked privately to your on-chain address.",
    collateralDiscount: "-15% Collateral",
    rateDiscount: "-0.8% Rate",
    icon: Shield,
    method: "Government ID cryptographic attestation"
  },
  {
    id: 3,
    title: "On-Chain Repayment History",
    description: "Positive score generated by history of clean repayment in other lending vaults.",
    collateralDiscount: "-10% Collateral",
    rateDiscount: "-0.6% Rate",
    icon: FileCheck,
    method: "Base network historical trace scanning"
  },
  {
    id: 4,
    title: "Default Reporting Consent",
    description: "Borrower opts into TEE-encrypted default reporting trigger to credit bureaus.",
    collateralDiscount: "-8% Collateral",
    rateDiscount: "-0.4% Rate",
    icon: Lock,
    method: "Cryptographic Consent Encrypted Attestation"
  }
];

/* ── Main Page Component ───────────────────────────────────────── */

export default function ApplyPage() {
  const { address, isConnected } = useAccount();
  const [currentStep, setCurrentStep] = useState(0);
  const { success: showSuccess, error: showError, pending: showPending } = useToast();

  // Live contract reads
  const poolRead = useRialoPoolRead(address);
  const liveCredentials = useMemo(() => {
    return poolRead.credentials.data
      ? [...poolRead.credentials.data]
      : [false, false, false, false, false];
  }, [poolRead.credentials.data]);

  // Enclave / Attestation signing and contract posting states
  const [attestingId, setAttestingId] = useState<number | null>(null);
  const verifierWrite = useCredentialVerifierWrite();

  // Mint faucet faucet writes
  const faucets = useRialoFaucets();

  // Slider inputs
  const [borrowAmount, setBorrowAmount] = useState<number>(60000);
  const [loanDurationDays, setLoanDurationDays] = useState<number>(90);

  // Borrow writes
  const borrowWrite = useRialoBorrowWrite();

  // ── Toast Notifications loop ──
  // Watch Attestation confirmations
  useEffect(() => {
    if (verifierWrite.txHash) {
      if (verifierWrite.isConfirmed) {
        showSuccess("Attestation Confirmed!", "Your credential is secure on-chain.", verifierWrite.txHash);
      } else {
        showPending("Securing Attestation", "Registering secure enclave signature...", verifierWrite.txHash);
      }
    }
  }, [verifierWrite.txHash, verifierWrite.isConfirmed]);

  // Watch Approval confirmations
  useEffect(() => {
    if (borrowWrite.approveHash) {
      if (borrowWrite.isApproveSuccess) {
        showSuccess("Approval Confirmed", "RLO collateral authorized for deposit.", borrowWrite.approveHash);
      } else {
        showPending("RLO Approval", "Approving collateral transfer in your wallet...", borrowWrite.approveHash);
      }
    }
  }, [borrowWrite.approveHash, borrowWrite.isApproveSuccess]);

  // Watch Borrow confirmations
  useEffect(() => {
    if (borrowWrite.borrowHash) {
      if (borrowWrite.isBorrowSuccess) {
        showSuccess("Borrow Successful!", "USDC has been deposited in your wallet.", borrowWrite.borrowHash);
      } else {
        showPending("Borrowing USDC", "Locking RLO collateral and issuing USDC...", borrowWrite.borrowHash);
      }
    }
  }, [borrowWrite.borrowHash, borrowWrite.isBorrowSuccess]);

  // Watch Faucet confirmations
  useEffect(() => {
    if (faucets.rloHash) {
      if (faucets.isRloSuccess) {
        showSuccess("RLO Minted!", "100,000 RLO collateral added to your wallet.", faucets.rloHash);
      } else {
        showPending("Minting RLO Faucet", "Claiming test RLO from faucet...", faucets.rloHash);
      }
    }
  }, [faucets.rloHash, faucets.isRloSuccess]);

  useEffect(() => {
    if (faucets.usdcHash) {
      if (faucets.isUsdcSuccess) {
        showSuccess("USDC Minted!", "1,000 USDC added to your wallet.", faucets.usdcHash);
      } else {
        showPending("Minting USDC Faucet", "Claiming test USDC from faucet...", faucets.usdcHash);
      }
    }
  }, [faucets.usdcHash, faucets.isUsdcSuccess]);

  // Map credentials state for pricing utility
  const mappedCredState = useMemo(() => {
    return {
      credit: liveCredentials[0],
      bank: liveCredentials[1],
      identity: liveCredentials[2],
      history: liveCredentials[3],
      reporting: liveCredentials[4],
    };
  }, [liveCredentials]);

  // Compute pricing details in real-time
  const pricingDetails = useMemo(() => {
    return computeCollateralDetails(mappedCredState, borrowAmount, 1.0);
  }, [mappedCredState, borrowAmount]);

  // Live balances formatted
  const rloBalanceDisplay = useMemo(() => {
    if (poolRead.rloBalance.data) {
      return Number(formatUnits(poolRead.rloBalance.data as bigint, 18)).toLocaleString(undefined, { maximumFractionDigits: 2 });
    }
    return "0.00";
  }, [poolRead.rloBalance.data]);

  const usdcBalanceDisplay = useMemo(() => {
    if (poolRead.usdcBalance.data) {
      return Number(formatUnits(poolRead.usdcBalance.data as bigint, 6)).toLocaleString(undefined, { maximumFractionDigits: 2 });
    }
    return "0.00";
  }, [poolRead.usdcBalance.data]);

  // Verification step helper: simulated/cryptographic enclave check
  const handleVerifyCredential = async (id: number) => {
    if (!address) return;
    setAttestingId(id);
    try {
      // 1. Fetch TEE enclave cryptographic signature
      const response = await fetch("/api/verify-credential", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ address, credentialId: id })
      });
      const data = await response.json();
      if (data.error) throw new Error(data.error);

      // 2. Post attestation signature live on-chain
      await verifierWrite.verifyAndRecord(address, id, data.payloadHash, data.signature);
      // Wait for on-chain confirmation (handled in useEffect)
    } catch (err) {
      console.error("Attestation failed:", err);
      setAttestingId(null);
    }
  };

  // Re-fetch pool state on success
  useEffect(() => {
    if (verifierWrite.isConfirmed && attestingId !== null) {
      poolRead.credentials.refetch().then(() => {
        setAttestingId(null);
      });
    }
  }, [verifierWrite.isConfirmed, attestingId]);

  useEffect(() => {
    if (faucets.isRloSuccess) {
      poolRead.rloBalance.refetch();
      poolRead.rloAllowance.refetch();
    }
    if (faucets.isUsdcSuccess) {
      poolRead.usdcBalance.refetch();
      poolRead.usdcAllowance.refetch();
    }
  }, [faucets.isRloSuccess, faucets.isUsdcSuccess]);

  useEffect(() => {
    if (borrowWrite.isApproveSuccess) {
      poolRead.rloAllowance.refetch();
    }
  }, [borrowWrite.isApproveSuccess]);

  // 2-Step borrow execution logic
  const requiredRloRaw = parseUnits(pricingDetails.collateralRlo.toString(), 18);
  const currentRloAllowance = (poolRead.rloAllowance.data as bigint) || 0n;
  const isRloApproved = currentRloAllowance >= requiredRloRaw;

  const handleApproveRLO = async () => {
    try {
      await borrowWrite.approveRlo(requiredRloRaw);
    } catch (err) {
      console.error("Approve failed:", err);
    }
  };

  const handleExecuteBorrow = async () => {
    try {
      const usdcBorrowAmount = parseUnits(borrowAmount.toString(), 6);
      const durationSeconds = BigInt(loanDurationDays * 24 * 60 * 60);
      await borrowWrite.borrow(usdcBorrowAmount, durationSeconds);
      setCurrentStep(3);
    } catch (err) {
      console.error("Borrow execution failed:", err);
    }
  };

  const numVerified = liveCredentials.filter(Boolean).length;

  return (
    <div className="min-h-screen pt-24 pb-24 px-4 md:px-8">
      {/* Dynamic Background */}
      <div className="fixed inset-0 pointer-events-none -z-10 overflow-hidden">
        <div
          className="absolute -top-[10%] -right-[10%] w-[60%] h-[60%] rounded-full opacity-5"
          style={{ background: 'radial-gradient(circle, var(--color-sage) 0%, transparent 70%)', filter: 'blur(100px)' }}
        />
        <div
          className="absolute -bottom-[10%] -left-[10%] w-[60%] h-[60%] rounded-full opacity-5"
          style={{ background: 'radial-gradient(circle, var(--color-bone) 0%, transparent 70%)', filter: 'blur(100px)' }}
        />
      </div>

      <div className="max-w-4xl mx-auto">
        {/* Step Indicator */}
        {isConnected && currentStep < 3 && <StepIndicator currentStep={currentStep + 1} />}

        {/* ── Wallet Connection Failsafe ── */}
        {!isConnected && (
          <div className="text-center py-16 fade-up">
            <Badge variant="outline" className="mb-6 py-1 px-3 border-accent/30 text-accent-foreground uppercase tracking-widest font-mono text-[9px]">
              Credential-Based Lending
            </Badge>
            <h1 className="heading-display mb-6 text-foreground">
              Borrow with <span className="italic" style={{ fontFamily: 'Newsreader, serif' }}>Trust,</span> not over-collateralization.
            </h1>
            <p className="text-base text-muted-foreground leading-relaxed mb-10 max-w-md mx-auto">
              Prove traditional credit history and bank reserves privately using secure enclaves to reduce your collateral up to 83%.
            </p>

            <div className="card p-12 border-dashed border-2 border-border bg-[var(--glass-bg)] flex flex-col items-center justify-center max-w-sm mx-auto">
              <Fingerprint className="size-10 text-muted-foreground/40 mb-4 animate-pulse" />
              <p className="font-mono text-xs tracking-tighter uppercase mb-2 text-foreground">Awaiting Wallet Connection</p>
              <p className="text-xs text-muted-foreground mb-4">Please connect your Web3 wallet to launch</p>
            </div>
          </div>
        )}

        {/* ── Step 01: Trust Credential Registry ── */}
        {isConnected && currentStep === 0 && (
          <div className="fade-up">
            <header className="mb-8">
              <Badge className="bg-[var(--color-sage-light)] text-[var(--color-sage-text)] font-mono border-none py-1 mb-2">
                Step 1 of 3
              </Badge>
              <h2 className="heading-2 text-foreground mb-2">Cryptographic Attestation Registry</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Interact with our off-chain Secure Enclave (TEE) to verify your assets, bureau history, and legal identity.
                Attesting credentials adds structural credibility, additively dropping both your APR and collateral requirements.
              </p>
            </header>

            {/* Live Progress Bar */}
            <Card className="border-none bg-[var(--glass-bg)] mb-8 p-6">
              <div className="flex items-center justify-between mb-3 text-xs font-mono">
                <span className="text-muted-foreground">ATTENSION INTEGRITY:</span>
                <span className="font-bold text-[var(--color-sage-text)]">{numVerified} / 5 SECURED</span>
              </div>
              <div className="h-2 bg-[var(--bone)] rounded-full overflow-hidden flex">
                <div
                  className="h-full bg-[var(--color-sage-dark)] transition-all duration-700"
                  style={{ width: `${(numVerified / 5) * 100}%` }}
                />
              </div>
              {numVerified === 5 && (
                <div className="mt-4 flex items-center gap-2 text-xs text-[var(--color-sage-text)] font-mono">
                  <Sparkles className="size-4 animate-bounce" />
                  <span>COMBO BONUS UNLOCKED: -5% collateral, -0.3% rate active!</span>
                </div>
              )}
            </Card>

            {/* List of 5 credentials */}
            <div className="space-y-4 mb-10">
              {CREDENTIAL_ITEMS.map((item) => {
                const isVerified = liveCredentials[item.id];
                const isCurrentAttesting = attestingId === item.id || (verifierWrite.isPending && attestingId === item.id);
                const Icon = item.icon;

                return (
                  <Card
                    key={item.id}
                    className={`border transition-all duration-300 bg-[var(--glass-bg)] overflow-hidden ${
                      isVerified
                        ? "border-[var(--color-sage)]/40 shadow-sm"
                        : "border-border hover:border-primary/20"
                    }`}
                  >
                    <div className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                      <div className="flex gap-4 items-start">
                        <div
                          className={`p-3 rounded-lg border transition-colors ${
                            isVerified
                              ? "bg-[var(--color-sage-light)]/40 border-[var(--color-sage)]/20 text-[var(--color-sage-text)]"
                              : "bg-[var(--bone)] border-border text-muted-foreground"
                          }`}
                        >
                          <Icon className="size-5" />
                        </div>
                        <div>
                          <h4 className="text-sm font-semibold text-foreground flex items-center gap-2">
                            {item.title}
                            {isVerified && (
                              <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[8px] font-bold font-mono tracking-widest bg-[var(--color-sage-light)] text-[var(--color-sage-text)] uppercase">
                                SECURED ✓
                              </span>
                            )}
                          </h4>
                          <p className="text-xs text-muted-foreground mt-0.5 max-w-md">{item.description}</p>
                          <p className="text-[10px] font-mono text-muted-foreground mt-1 opacity-55">
                            Verify method: {item.method}
                          </p>
                        </div>
                      </div>

                      <div className="flex sm:flex-col items-end gap-2 shrink-0 self-end sm:self-center">
                        <div className="text-right">
                          <span className="block text-[10px] font-mono font-bold text-[var(--color-sage-text)]">{item.collateralDiscount}</span>
                          <span className="block text-[9px] font-mono text-muted-foreground">{item.rateDiscount}</span>
                        </div>
                        
                        {!isVerified ? (
                          <Button
                            size="sm"
                            disabled={attestingId !== null}
                            onClick={() => handleVerifyCredential(item.id)}
                            className="h-8 px-4 font-mono text-[9px] uppercase tracking-widest bg-[var(--color-sage-dark)] hover:bg-[var(--color-sage-text)] text-white shadow-sm flex items-center gap-1.5"
                          >
                            {isCurrentAttesting ? (
                              <>
                                <RefreshCw className="size-3 animate-spin" />
                                ATTESTING...
                              </>
                            ) : (
                              <>
                                <Plus className="size-3" />
                                ATTEST
                              </>
                            )}
                          </Button>
                        ) : (
                          <div className="size-6 rounded-full bg-[var(--color-sage-light)] flex items-center justify-center text-[var(--color-sage-text)]">
                            <Check className="size-3.5 stroke-[3]" />
                          </div>
                        )}
                      </div>
                    </div>
                  </Card>
                );
              })}
            </div>

            <div className="flex justify-end pt-4 border-t border-border">
              <Button
                onClick={() => setCurrentStep(1)}
                className="btn-primary px-10 h-12"
              >
                Configure Borrowing Terms →
              </Button>
            </div>
          </div>
        )}

        {/* ── Step 02: Loan Slider & Terms Config ── */}
        {isConnected && currentStep === 1 && (
          <div className="fade-up">
            <header className="mb-8">
              <Badge className="bg-[var(--color-sage-light)] text-[var(--color-sage-text)] font-mono border-none py-1 mb-2">
                Step 2 of 3
              </Badge>
              <h2 className="heading-2 text-foreground mb-2">Tailor Loan Parameters</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Synchronized live with the `RialoLendingPool` pricing contract. Adjust amount and duration to review RLO collateral ratios and interest terms.
              </p>
            </header>

            {/* Parameters Read-out */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <Card className="border-none bg-[var(--glass-bg)] p-5">
                <p className="text-[10px] font-mono tracking-widest text-muted-foreground uppercase mb-1">Required LTV Ratio</p>
                <div className="flex items-baseline gap-2">
                  <span className="heading-3 text-foreground">{pricingDetails.collateralRatio}%</span>
                  {pricingDetails.collateralRatio < 150 && (
                    <span className="text-[10px] font-mono text-[var(--color-sage-text)]">
                      (-{150 - pricingDetails.collateralRatio}%)
                    </span>
                  )}
                </div>
              </Card>

              <Card className="border-none bg-[var(--glass-bg)] p-5">
                <p className="text-[10px] font-mono tracking-widest text-muted-foreground uppercase mb-1">Active Borrow APR</p>
                <div className="flex items-baseline gap-2">
                  <span className="heading-3 text-foreground">{pricingDetails.interestRate}%</span>
                  {pricingDetails.interestRate < 12.5 && (
                    <span className="text-[10px] font-mono text-[var(--color-sage-text)]">
                      (-{(12.5 - pricingDetails.interestRate).toFixed(1)}%)
                    </span>
                  )}
                </div>
              </Card>

              <Card className="border-none bg-primary text-primary-foreground p-5">
                <p className="text-[10px] font-mono tracking-widest text-primary-foreground/50 uppercase mb-1">Capital Saved</p>
                <span className="heading-3 text-[var(--color-sage)] font-bold">
                  ${pricingDetails.capitalFreedUsd.toLocaleString()}
                </span>
              </Card>
            </div>

            {/* Inputs Section */}
            <Card className="border-none bg-[var(--glass-bg)] p-6 mb-8 space-y-8">
              {/* Slider 1: Loan Amount */}
              <div className="space-y-4">
                <div className="flex justify-between items-baseline">
                  <Label className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">USDC Borrow Amount</Label>
                  <span className="font-mono font-bold text-foreground text-lg">${borrowAmount.toLocaleString()} USDC</span>
                </div>
                <input
                  type="range"
                  min="10000"
                  max="1000000"
                  step="5000"
                  value={borrowAmount}
                  onChange={(e) => setBorrowAmount(Number(e.target.value))}
                  className="w-full accent-[var(--color-sage-dark)] h-1 bg-[var(--bone)] rounded-lg appearance-none cursor-pointer"
                />
                <div className="flex justify-between text-[9px] font-mono text-muted-foreground opacity-50">
                  <span>MIN: $10,000</span>
                  <span>MAX: $1,000,000</span>
                </div>
              </div>

              {/* Slider 2: Duration */}
              <div className="space-y-4">
                <div className="flex justify-between items-baseline">
                  <Label className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Loan Duration Term</Label>
                  <span className="font-mono font-bold text-foreground text-lg">{loanDurationDays} Days</span>
                </div>
                <input
                  type="range"
                  min="7"
                  max="365"
                  step="1"
                  value={loanDurationDays}
                  onChange={(e) => setLoanDurationDays(Number(e.target.value))}
                  className="w-full accent-[var(--color-sage-dark)] h-1 bg-[var(--bone)] rounded-lg appearance-none cursor-pointer"
                />
                <div className="flex justify-between text-[9px] font-mono text-muted-foreground opacity-50">
                  <span>MIN: 7 DAYS</span>
                  <span>MAX: 365 DAYS</span>
                </div>
              </div>
            </Card>

            {/* RLO Balance & Faucet Notification */}
            <Card className="border-none bg-[var(--glass-bg)] p-6 mb-10">
              <h4 className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground mb-4">RLO Collateral Status</h4>
              
              <div className="grid grid-cols-2 gap-4 items-center mb-6">
                <div>
                  <p className="text-[10px] font-mono text-muted-foreground opacity-50">Required Collateral</p>
                  <p className="font-mono text-sm font-semibold text-foreground">{pricingDetails.collateralRlo.toLocaleString()} RLO</p>
                </div>
                <div>
                  <p className="text-[10px] font-mono text-muted-foreground opacity-50">Your RLO Balance</p>
                  <p className="font-mono text-sm font-semibold text-foreground">{rloBalanceDisplay} RLO</p>
                </div>
              </div>

              {poolRead.rloBalance.data !== undefined && (poolRead.rloBalance.data as bigint) < requiredRloRaw ? (
                <div className="p-4 rounded-lg bg-amber-500/10 border border-amber-500/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                  <div className="flex gap-2.5 items-start sm:items-center text-amber-600">
                    <AlertCircle className="size-4 shrink-0 mt-0.5 sm:mt-0" />
                    <span className="text-xs font-semibold">Insufficient RLO collateral to lock for this loan size.</span>
                  </div>
                  <Button
                    size="sm"
                    disabled={faucets.isMintingRlo}
                    onClick={() => faucets.requestRloFaucet()}
                    className="h-8 px-4 font-mono text-[9px] uppercase tracking-widest bg-amber-600 hover:bg-amber-700 text-white shadow-sm shrink-0"
                  >
                    {faucets.isMintingRlo ? "Minting..." : "Claim 100k RLO Faucet"}
                  </Button>
                </div>
              ) : (
                <div className="p-4 rounded-lg bg-[var(--color-sage-light)]/20 border border-[var(--color-sage)]/20 text-[var(--color-sage-text)] flex items-center gap-2">
                  <Check className="size-4 shrink-0" />
                  <span className="text-xs font-semibold">Collateral threshold satisfied. Ready to proceed.</span>
                </div>
              )}
            </Card>

            <div className="flex justify-between items-center pt-4 border-t border-border">
              <Button onClick={() => setCurrentStep(0)} variant="outline" className="px-6">← Edit Trust Profile</Button>
              <Button
                onClick={() => setCurrentStep(2)}
                disabled={poolRead.rloBalance.data === undefined || (poolRead.rloBalance.data as bigint) < requiredRloRaw}
                className="btn-primary px-10 h-12"
              >
                Proceed to Checkout →
              </Button>
            </div>
          </div>
        )}

        {/* ── Step 03: Confirm Checkout (2-Step transaction approval) ── */}
        {isConnected && currentStep === 2 && (
          <div className="fade-up">
            <header className="mb-8 text-center">
              <Badge className="bg-[var(--color-sage-light)] text-[var(--color-sage-text)] font-mono border-none py-1 mb-2">
                Checkout Summary
              </Badge>
              <h2 className="heading-2 text-foreground mb-1">Verify and Secure Position</h2>
              <p className="text-xs text-muted-foreground">
                Authorize on-chain RLO collateral deposit and execute dynamic USDC loan issuance.
              </p>
            </header>

            {/* Position Summary Card */}
            <Card className="border-none bg-[var(--glass-bg)] mb-8 overflow-hidden">
              <div className="p-6 bg-muted/40 border-b border-border flex justify-between items-baseline">
                <span className="text-[10px] font-mono uppercase text-muted-foreground tracking-widest">Borrowing Principal</span>
                <span className="heading-3 text-foreground">${borrowAmount.toLocaleString()} USDC</span>
              </div>
              <div className="p-6 space-y-4">
                <div className="flex justify-between items-baseline text-xs font-mono">
                  <span className="text-muted-foreground uppercase">Collateral Ratio</span>
                  <span className="font-semibold text-foreground">{pricingDetails.collateralRatio}%</span>
                </div>
                <div className="flex justify-between items-baseline text-xs font-mono">
                  <span className="text-muted-foreground uppercase">Locked Collateral</span>
                  <span className="font-semibold text-foreground">{pricingDetails.collateralRlo.toLocaleString()} RLO</span>
                </div>
                <div className="flex justify-between items-baseline text-xs font-mono">
                  <span className="text-muted-foreground uppercase">Borrowing APR</span>
                  <span className="font-semibold text-foreground">{pricingDetails.interestRate}% APR</span>
                </div>
                <div className="flex justify-between items-baseline text-xs font-mono">
                  <span className="text-muted-foreground uppercase">Loan Duration Term</span>
                  <span className="font-semibold text-foreground">{loanDurationDays} Days</span>
                </div>
              </div>
            </Card>

            {/* Faucet Box in case they run out of ETH gas */}
            <div className="p-4 bg-muted border border-border rounded-lg mb-8 flex justify-between items-center text-xs font-mono">
              <span className="text-muted-foreground">Gas/Liquidity faucet:</span>
              <div className="flex gap-2">
                <Button size="sm" onClick={() => faucets.requestUsdcFaucet()} disabled={faucets.isMintingUsdc} variant="outline" className="h-7 text-[8px] uppercase tracking-widest">
                  {faucets.isMintingUsdc ? "Minting..." : "Mint USDC"}
                </Button>
              </div>
            </div>

            {/* Checkout Action Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10">
              {/* Tx 1: Approve */}
              <Card className={`p-6 border transition-all duration-300 flex flex-col justify-between ${
                isRloApproved 
                  ? "border-[var(--color-sage)]/40 bg-[var(--color-sage-light)]/5"
                  : "border-border bg-[var(--glass-bg)]"
              }`}>
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <Badge variant="outline" className="font-mono text-[9px] uppercase tracking-wider">Transaction 01</Badge>
                    {isRloApproved && (
                      <span className="text-[9px] font-mono text-[var(--color-sage-text)] font-bold">APPROVED ✓</span>
                    )}
                  </div>
                  <h4 className="text-sm font-bold text-foreground mb-2">Approve RLO Collateral</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed mb-6">
                    Approve the RialoLendingPool smart contract to secure and lock {pricingDetails.collateralRlo.toLocaleString()} RLO collateral from your wallet.
                  </p>
                </div>
                <Button
                  disabled={isRloApproved || borrowWrite.isApproving}
                  onClick={handleApproveRLO}
                  className={`w-full font-mono text-[10px] uppercase tracking-widest h-11 ${
                    isRloApproved
                      ? "bg-[var(--color-sage-light)] text-[var(--color-sage-text)] border border-[var(--color-sage)]/30 hover:bg-[var(--color-sage-light)]"
                      : "bg-[var(--color-sage-dark)] hover:bg-[var(--color-sage-text)] text-white"
                  }`}
                >
                  {borrowWrite.isApproving ? "Confirming..." : isRloApproved ? "Approved" : "Approve RLO"}
                </Button>
              </Card>

              {/* Tx 2: Borrow */}
              <Card className={`p-6 border transition-all duration-300 flex flex-col justify-between ${
                !isRloApproved
                  ? "opacity-50 pointer-events-none border-border bg-[var(--glass-bg)]"
                  : "border-border bg-[var(--glass-bg)]"
              }`}>
                <div>
                  <Badge variant="outline" className="font-mono text-[9px] uppercase tracking-wider mb-4">Transaction 02</Badge>
                  <h4 className="text-sm font-bold text-foreground mb-2">Execute Borrow Request</h4>
                  <p className="text-xs text-muted-foreground leading-relaxed mb-6">
                    Sign standard on-chain call to deposit RLO collateral into the pool and receive {borrowAmount.toLocaleString()} USDC directly in your address.
                  </p>
                </div>
                <Button
                  disabled={!isRloApproved || borrowWrite.isBorrowing}
                  onClick={handleExecuteBorrow}
                  className="w-full font-mono text-[10px] uppercase tracking-widest h-11 bg-primary text-primary-foreground"
                >
                  {borrowWrite.isBorrowing ? "Borrowing..." : "Confirm & Borrow"}
                </Button>
              </Card>
            </div>

            {/* Error notifications */}
            {borrowWrite.borrowError && (
              <Alert variant="destructive" className="mb-8">
                <AlertTitle>Transaction Failed</AlertTitle>
                <AlertDescription>{borrowWrite.borrowError.message}</AlertDescription>
              </Alert>
            )}

            <div className="flex justify-start">
              <Button onClick={() => setCurrentStep(1)} variant="outline" disabled={borrowWrite.isBorrowing || borrowWrite.isApproving} className="px-6">← Edit Terms</Button>
            </div>
          </div>
        )}

        {/* ── Step 04: Checkout Success ── */}
        {isConnected && currentStep === 3 && (
          <div className="text-center fade-up py-12">
            {!borrowWrite.isBorrowSuccess ? (
              <div className="py-12 flex flex-col items-center justify-center">
                <div className="relative w-20 h-20 mb-8">
                  <div className="absolute inset-0 rounded-full border-4 border-[var(--color-sage)]/25" />
                  <div className="absolute inset-0 rounded-full border-4 border-[var(--color-sage-dark)] border-t-transparent animate-spin" />
                </div>
                <h2 className="heading-3 text-2xl mb-4 text-foreground">Deploying Capital On-Chain...</h2>
                <p className="text-xs text-[var(--ink-muted)] max-w-sm mx-auto leading-relaxed">
                  Securing your RLO collateral and deploying USDC funds on Base Sepolia. This takes approximately 3-5 seconds.
                </p>
                {borrowWrite.borrowHash && (
                  <p className="text-[9px] font-mono text-muted-foreground opacity-55 mt-4 break-all max-w-xs mx-auto">
                    Tx: {borrowWrite.borrowHash}
                  </p>
                )}
              </div>
            ) : (
              <>
                <div className="w-20 h-20 rounded-full bg-[var(--color-sage-light)] flex items-center justify-center mx-auto mb-8 shadow-[0_0_40px_rgba(140,196,184,0.3)]">
                  <Check className="size-8 text-[var(--color-sage-text)] stroke-[3]" />
                </div>
                <h1 className="heading-display mb-4">Capital Deployed.</h1>
                <p className="text-base text-[var(--ink-muted)] mb-10 max-w-sm mx-auto">
                  Your under-collateralized loan of **${borrowAmount.toLocaleString()} USDC** is confirmed and processed on Base Sepolia.
                </p>

                <Card className="p-6 border-none bg-[var(--glass-bg)] mb-10 max-w-md mx-auto">
                  <p className="text-[10px] text-[var(--ink-muted)] mb-2 font-mono uppercase tracking-widest">Attestation Details</p>
                  <div className="space-y-3 font-mono text-[10px] text-left">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">COLLATERAL SECURED:</span>
                      <span className="text-foreground">{pricingDetails.collateralRlo.toLocaleString()} RLO</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">REPAYMENT APR:</span>
                      <span className="text-foreground">{pricingDetails.interestRate}%</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">TRANSACTION HASH:</span>
                      <a
                        href={`https://sepolia.basescan.org/tx/${borrowWrite.borrowHash}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[var(--color-sage-text)] hover:underline truncate max-w-[180px] block"
                      >
                        {borrowWrite.borrowHash}
                      </a>
                    </div>
                  </div>
                </Card>

                <Link href="/dashboard">
                  <Button className="btn-primary max-w-sm w-full py-6">
                    Enter Command Center Dashboard
                  </Button>
                </Link>
              </>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
